#!/usr/bin/env bash
#  Bash script that will display information about subdomains.
# Check if domain argument is provided

# Function to display subdomain information
display_info() {
    local domain="$1"
    local subdomain="$2"
    local records=("www" "lb-01" "web-01" "web-02")

  # Check if subdomain is provided, otherwise use default subdomains
  if [ -n "$subdomain" ]; then
    records=("$subdomain")
  fi
  # Iterate through subdomains and display information
  for sub in "${records[@]}"; do
    dig_output=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '/IN/ {print $4}')
    destination=$(echo "$dig_output" | awk '/IN/ {print $5}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

display_info "$1" "$2"
