#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a custom HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx
sudo service nginx restart
