#!/usr/bin/env bash
#installs nginx server

# Update
apt-get -y update
apt-get -y upgrade

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
# HAProxy configuration to haproxy.cfg

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 234523-web-01 18.234.105.167:80 check
    server 234523-web-02 100.25.222.179:80 check
"

# Start the HAProxy service
sudo service haproxy start#!/usr/bin/env bash
# Install HAproxy if not installed
if ! command -v haproxy &>/dev/null; then
    sudo apt-get -y update
    sudo apt-get -y install --no-install-recommends software-properties-common
    sudo add-apt-repository ppa:vbernat/haproxy-2.8
    sudo apt-get -y install haproxy=2.8.\*
fi

# Define the backend server addresses and ports
web_01_address="100.26.231.64"
web_02_address="107.23.16.147"
backend_port="80"

# Path to the haproxy.cfg file
haproxy_cfg="/etc/haproxy/haproxy.cfg"

# Append the desired configuration to the HAProxy configuration file using sudo tee
sudo tee -a "$haproxy_cfg" <<EOL > /dev/null

frontend http-in
   bind *:80
   default_backend servers

backend servers
   balance roundrobin
   server web-01 $web_01_address:$backend_port check
   server web-02 $web_02_address:$backend_port check
EOL

#resart HAproxy
sudo service haproxy start
