#!/usr/bin/env bash
# Install HAproxy if not installed
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

sudo cp "/etc/haproxy/haproxy.cfg.bak" "/etc/haproxy/haproxy.cfg"
# Append the desired configuration to the HAProxy configuration file using sudo tee
echo "\
frontend http-in
   bind *:80
   mode http
   default_backend servers

backend servers
   balance roundrobin
   server web-01 100.26.231.64:80 check
   server web-02 107.23.16.147:80 check" | sudo tee -a "/etc/haproxy/haproxy.cfg" > /dev/null


#resart HAproxy
sudo service haproxy restart
