#!/usr/bin/env bash

# Install HAproxy if not installed
if ! command -v haproxy &>/dev/null; then
    sudo apt-get -y update
    sudo apt-get -y install --no-install-recommends software-properties-common
    sudo add-apt-repository ppa:vbernat/haproxy-2.8
    sudo apt-get -y install haproxy=2.8.\*
fi

haproxy_cfg="/etc/haproxy/haproxy.cfg"

# Create a backup of the original haproxy.cfg
sudo cp "$haproxy_cfg" "$haproxy_cfg.bak"

#Edit config file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOL

frontend http-in
   bind *:80
   default_backend servers

backend servers
   balance roundrobin
   server web-01 34.207.190.83:80 check
   server web-02 52.91.178.39:80 check
EOL

#resart HAproxy
sudo service haproxy restart
