#!/usr/bin/env bash

var=1

while [ $var -ne 21 ]
do

    case "$var" in
	4)  echo "$var"
	    echo bad luck from China
	   ;;
	9) echo "$var"
	   echo bad luck from Japan
	   ;;
	17) echo "$var"
	    echo bad luck from Italy
	    ;;
	*) echo "$var"
    esac
    ((var++))
done
