#!/usr/bin/env bash
#  displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed
FILE="/etc/passwd"

while IFS=':' read -r username _ uid _ _ home _
do
    echo "$username:$uid:$home"
done < "$FILE"
