#!/usr/bin/env bash
# configures the container to fit the below requirements:
#+    - nginx must be running as nginx user
#+    - nginx must be listening on all active IPs on port 8080

# Check if the "nginx" user and group exist; if not, create them
if ! id -u "nginx" &> /dev/null; then
    adduser --system --no-create-home --disabled-login --group nginx
fi

# Set nginx to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Ensure nginx is listening on all active IPs on port 8080
sudo sed -i '/^http {/a\        server {\n            listen 8080;\n            }' /etc/nginx/nginx.conf
